name = "beyond-wonderland"
description = "Hugo theme for “Festival from home”, because Bobby is salty about Beyond Wonderland 2020."
homepage = "https://github.com/festivalfromhome/beyond-wonderland"
tags = ["Hugo", "Tailwindcss"]
features = []
min_version = "0.41"

[author]
  name = "Bobby Chen"
  homepage = "https://github.com/chenbobby/"
